ktor {
  deployment { port = 8080 }
  application {
    modules = [ ru.escalop.app.AppKt.module ]
  }

  db {
    jdbcUrl = "jdbc:postgresql://localhost:5432/escalop"
    driverClassName = "org.postgresql.Driver"
    username = "escalop"
    password = "escalop"
  }
}